### ISSUE TITLE
Unable to get any stats

### ISSUE THREAD

**Issue by Giggitybyte** [sirdoombox/Overwatch.Net#14]
The changes regarding TLS 1.2 seems to have broken lookups altogether for .Net Core.
I have tried on .Net Core 2.0 as well as .Net Core 2.1 and I get the [same exception](https://x0.at/lY3.png).

If it helps, I'm running Windows 10 and Visual Studio 2017 Community.

**Comment by sirdoombox** [comment]
I'm on Win10 as well, I was having problems **without** it though, it seems support for TLS12 is all over the shop and right now I'm between a rock and a hard place with it.

The tests are all running on framework 4.6.2, and are running fine there.

I'm not up to speed on NetCore the only thing I could really find on the issue was this

**Comment by sirdoombox** [comment]
I ran an analysis on PlayOverwatch and it does seem to support TLS 1.1 as an alternative to 1.2

If you happen to have a local copy you could try this out for me and see if you get on with it, I don't have netcore set up on my machine in any capacity right now.
`HttpProfileClient.cs` in `OverwatchAPI/Core/WebClient/`
switching line 17 from this...
```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls11;
```
to just this
```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11;
```

**Comment by Giggitybyte** [comment]
Good news!

I changed line 17 like you asked and everything seems to work just fine. 
I'm able to get player data using TLS 1.1 with both .Net Core 2.0 and 2.1.

**Comment by sirdoombox** [comment]
Fix is implemented and will be up with the next release.
